### ISSUE TITLE
Repository License 

### ISSUE THREAD

**Issue by OutHouse2021** [VirtCode/SmartMouse#4]
Hello,

There is no license listed for this project? 

I would like to know what the license would be for this project.

Thanks.

**Comment by OutHouse2021** [comment]
@VirtCode

**Comment by VirtCode** [comment]
Hey, thanks for reaching out!
There is currently indeed no license because I haven't yet decided on where i want to go with this project.
But I'll think about it for a while and will choose one in the coming days.

In the meantime, may I ask what you intend to do with the project once I've licensed it?

**Comment by OutHouse2021** [comment]
Hello, great to hear back from you!

I am currently starting a similar project to control a computer with a remote android app using motion from the devices camera and I notice your Bluetooth connectivity component is similar to what I need. Therefore I wanted to use an adaption of your component.

Thank you!

**Comment by VirtCode** [comment]
I have now ultimately decided to license it under the GPLv3 (as seen in commit https://github.com/VirtCode/SmartMouse/commit/a518bfd22fce325bfa5742e141d8aaaa6e03dfa1).
This is mostly due to the position estimation algorithm which is the main part of this project.

I hope you can use the code here, and wish you the best with your project - it sound quite interesting!
